### ISSUE TITLE
Release v3

### ISSUE THREAD

**Issue by thgh** [thgh/rollup-plugin-scss#68]
Some todos that would be nice to check off before releasing v3.

- [ ]  Double check if README is clear
- [x]  Add more examples in README (e.g. `includePath`, `processor()`)
- [x]  Rollup v0 case
- [x]  Typescript type definitions #55
- [x]  Add sourcemaps #66
- [x]  Add test for #66
- [x]  Remove node-sass from dependencies #65 
- [x]  Update README to include installation instructions for v3 #65 
- [x]  Update README to include installation instructions for v2 #65 
- [x]  Add `insert` option #63 
- [x]  Add test for #63 
- [x]  Automate testing with Github Actions
- [x]  Add support for yarn PnP #83
- [x]  Update CHANGELOG
- [ ]  Update contributors

**Comment by thgh** [comment]
v3.0.0-rc1 has been released, install with:

```
npm install --save-dev rollup-plugin-scss@rc

yarn add -D rollup-plugin-scss@rc
```

Feedback welcome!

**Comment by FlorianWendelborn** [comment]
> Feedback welcome

<https://github.com/thgh/rollup-plugin-scss/issues/61#issuecomment-820530301>

**Comment by mauritzn** [comment]
@thgh any idea when `v3` will get the full release _(aka no longer be a pre-release version)_? Mainly wondering since it has been quite a while already since `v3.0.0-rc1` came out. Love that it's TypeScript now as well ❤️

**Comment by thgh** [comment]
There it is 🎉
